<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = 'id="' .$this->zoneconfig['conf']['id'] . '"';
?>
<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>" data-kevseal="teleport here">
    <div class="spacing-x2 innerAll">
        <?php
        echo '<br><pre>'.'tool-content-table-container.phtml';
        var_dump($this->zoneconfig);

        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
</div>