<?php
    $dataMelisKey = empty($this->melisKey)? 'melis_cms_page_analytics_page_table': $this->melisKey;
    $id = empty($this->zoneconfig['conf']['id'])? $this->pageHitId.'_id_melis_cms_page_analytics_page_table': $this->pageHitId.'_'.$this->zoneconfig['conf']['id'];
?>

<div id="<?= $id; ?>" data-melisKey="<?= $dataMelisKey; ?>" class="col-ms-12">
    <br>
    <?php
        $this->melisGenericTable()->setTable(array(
            'id' => $this->pageHitId . '_tableMelisCmsPageAnalyticsPageDetails',
            'class' => 'table table-striped table-primary dt-responsive nowrap',
            'cellspacing' => '0',
            'width' => '100%'
        ));
        $columns = array();
        $columnStyle = array();
        foreach($this->tableColumns as $columnText)
        {
            $columns[] = $columnText['text'];
        }
        $this->melisGenericTable()->setColumns($columns);
        echo $this->melisGenericTable()->renderTable();
    ?>
    <script type="text/javascript">
        $(document).ready(function() {
            <?= $this->getToolDataTableConfig; ?>

            /**
             * Deletes the Caret in the First Column
             */
            var searchTable = setInterval(function(){
                var pageAnalyticsTable = $body.find("#<?= $this->pageHitId . '_tableMelisCmsPageAnalyticsPageDetails'?> thead tr th:first-child.sorting_asc");
                if(pageAnalyticsTable.length)
                {
                    pageAnalyticsTable.removeClass('sorting_asc');
                    clearInterval(searchTable);
                }
            }, 300);
        });
    </script>
</div>