<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="spacing-x2 innerAll">
        <?php
       
        $this->melisGenericTable()->setTable(array(
            'id' => $this->pageHitId . '_tableMelisCmsPageAnalyticsPageDetails',
            'class' => 'table table-striped table-primary dt-responsive nowrap',
            'cellspacing' => '0',
            'width' => '100%'
        ));
        $columns = array();
        $columnStyle = array();
        foreach($this->tableColumns as $columnText)
        {
            $columns[] = $columnText['text'];

        }
        // print_r($columns);
        $this->melisGenericTable()->setColumns($columns);

        echo $this->melisGenericTable()->renderTable();
        ?>
        <script type="text/javascript">
            $(document).ready(function() {
                <?= $this->getToolDataTableConfig; ?>
            });
        </script>
    </div>
</div>
