-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 15:59:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melis-cms-page-analytics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_page_analytics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_analytics` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_analytics` (
  `ph_id` INT NOT NULL AUTO_INCREMENT,
  `ph_page_id` INT NOT NULL,
  `ph_session_id` VARCHAR(100) NOT NULL,
  `ph_date_visit` DATETIME NULL,
  `ph_site_id` INT NULL,
  PRIMARY KEY (`ph_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_page_analytics_data_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_analytics_data_settings` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_analytics_data_settings` (
  `pads_id` INT NOT NULL AUTO_INCREMENT,
  `pads_site_id` INT NOT NULL,
  `pads_analytics_key` VARCHAR(100) NOT NULL,
  `pads_settings` LONGTEXT NULL,
  `pads_js_analytics` LONGTEXT NULL,
  PRIMARY KEY (`pads_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_page_analytics_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_analytics_data` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_analytics_data` (
  `pad_id` INT NOT NULL AUTO_INCREMENT,
  `pad_site_id` INT NOT NULL,
  `pad_analytics_key` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pad_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
