<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';

$form = $this->form;
//Analytics Settings Tab Content
if ($this->hasAccess) { ?>
    <!-- Tab content -->
    <div <?php echo $id; ?> class="meliscms_center_tabs tab-pane clearfix">
        <?= $this->form()->openTag($form); ?>
        <?= $this->melisFieldCollection($form); ?>
        <div id="analytics-settings-form"></div>
        <span id="pads_js_analytics_cont" class="hidden">
            <label for="pas_js_analytics"><?= $this->translate('tr_meliscms_page_analytics_site_analytics_script'); ?></label>
            <i class="fa fa-info-circle fa-lg pull-right tip-info" data-toggle="tooltip" data-placement="left" title=""
               data-original-title="<?= $this->translate('tr_meliscms_page_analytics_site_analytics_script_tooltip'); ?>"></i>
            <pre id="pads_js_analytics" name="pads_js_analytics"></pre>
        </span>
        <div class="clearfix">
            <div class="pull-right">
                <button type="submit" class="btn btn-success mcpa-save-settings" disabled="disabled"><i class="fa fa-save"></i> <?= $this->translate('tr_meliscore_tool_gen_save') ?></button>
            </div>
        </div>

        <div id="melis-cms-google-analytics-guidelines" class="row melis-cms-google-analytics-guidelines hidden">
            <div class="col-md-12">
                <?= $this->google_analytics_config_guide; ?>
            </div>
        </div>

        <div class="clearfix"></div>
        <?= $this->form()->closeTag(); ?>

        <script text="text/javascript">
            $(function () {
                var editor = ace.edit("pads_js_analytics");

                // Disable first select options
                $('select#page_analytics_id option:first-child').attr('disabled', 'true');
                $('form#select_page_analytic_form select#site_id option:first-child').attr('disabled', 'true');
            });
        </script>
    </div>
    <!-- // Tab content END -->
    <?php
}
?>