<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';

 $form = $this->form
?>

<div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
        <div class="widget-head nav">
            <ul class="tabs-label nav-tabs">

            <?php

                echo $this->meliscms_page_analytics_site_analytics_tab;
               echo $this->meliscms_page_analytics_site_analytics_tab_settings;
            
            ?>
            </ul>
        </div>
    </div>
    <div class="spacing-x2 innerAll">

        <div class="tab-content">

            <?php

                echo $this->meliscms_page_analytics_site_analytics_tab_content;
                echo $this->meliscms_page_analytics_site_analytics_tab_settings_content;
            ?>
        </div>

    </div>
</div>
