<?php
if($this->hasAccess) { ?>
                <li> <!--  id="1_id_meliscms_center_page_tabs_properties_title" -->
                    <a id="cms-page-anlytics-tab-settings-button" class="glyphicons cogwheel" data-page-id="1" data-toggle="tab" href="#tab-page-analytics-tool-settings">
                        <i> </i>
                        <span><?= $this->translate('tr_meliscms_page_analytics_settings'); ?></span>
                    </a>
                </li>
<?php
}
?>