<?php
if($this->hasAccess) { ?>
    <li class="nav-item active"> <!--  id="1_id_meliscms_center_page_tabs_edition_title" -->
        <a class="nav-link glyphicons stats" data-page-id="1" data-bs-toggle="tab" data-bs-target="#tab-page-analytics-tool" href="#tab-page-analytics-tool">
            <i> </i>
            <span><?= $this->translate('tr_meliscms_page_analytics_title'); ?></span>
        </a>
    </li>
<?php
}
?>