<?php
if($this->hasAccess)
{ 
	$this->melisGenericTable()->setTable(array(
	    'id' => 'tableMelisCmsPageAnalytics',
	    'class' => 'table table-striped table-primary dt-responsive nowrap',
	    'cellspacing' => '0',
	    'width' => '100%'
	));
	$columns = array();
	$columnStyle = array();
	foreach($this->tableColumns as $columnText)
	{
	    $columns[] = $columnText['text'];

	}
	// print_r($columns);
	$this->melisGenericTable()->setColumns($columns);

	echo $this->melisGenericTable()->renderTable();
	?>

	<!-- /CONTENT -->
	<script type="text/javascript">
	    $(document).ready(function() {
	        <?= $this->getToolDataTableConfig; ?>
	    });
	</script>
<?php
 }
?>